name: DockerCPU
# https://www.docker.com/blog/first-docker-github-action-is-here
# https://github.com/docker/build-push-action
# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:
    branches:
      - 'master'
      - 'main'


jobs:
  build-docker:
    runs-on: ubuntu-20.04
    timeout-minutes: 180

    strategy:
      fail-fast: false
      matrix:
        include:
          - {python: "3.9", pytorch: "1.10"}
          - {python: "3.9", pytorch: "1.11"}
          - {python: "3.9", pytorch: "1.12"}

    steps:
      #
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}
          tags: |
            type=raw,value=py${{ matrix.python }}-torch${{ matrix.pytorch }}-cpu

      - name: Build
        # publish master/release
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: cpu.Dockerfile
          platforms: linux/amd64
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            PYTORCH_VERSION=${{ matrix.pytorch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            maintainer=justusschock
            ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
